In [1]:
import numpy as np

In [4]:
data1 = [1,2,3]
data2 = [[1,2,3],[4,5,6]]

In [5]:
arr1 = np.array(data1)
arr2 = np.array(data2)

## 4.1.1 ndarrayの生成
### ndim 
return 配列の次元数

### shape
return 配列の次元ごとの要素数を格納するタプル

### dtype
return 要素の型

### ndarray生成関数
### array
省略

### asarray
arrayと同様だが、入力がndarrayだった場合は新規に変数を生成しない.

### zeros, zeros_like
指定されたサイズのndarrayを生成し、すべての要素に0を設定する　

### ones, ones_like
指定されたサイズのndarrayを生成し、すべての要素に1を設定する

### empty, empty_like
onesと同様にndarrayを生成するが, 各要素は初期化されず不定のまま.
=> 配列の領域のみをメモリ上に確保するだけ、値は不明になる.
=> 実行速度が高速なため、明示的な初期化が必要ない場面に使う.

### arange
range関数と同等の動作で、等間隔に増減させた値で要素を満たす

### full, full_like
指定されたサイズのndarrayを指定されたdtypeで生成, 要素を全て指定された値で埋める.

### eye, identity
N x Nの単位行列となるndarrayを生成する.

In [22]:
print(np.empty(3))
print(np.empty(3, dtype= np.bool)) #bool値にもできる
print(np.empty(4, dtype= complex)) #複素数にもできる

[2.68156159e+154 2.68156159e+154 1.48219694e-323]
[ True  True  True]
[-2.68156159e+154-2.68156159e+154j  2.47032823e-323+0.00000000e+000j
  0.00000000e+000+0.00000000e+000j -2.68156159e+154-2.68156159e+154j]


## 4.1.2 ndarrayのデータ型
dtypeはndarrayの$データ型$. 以下リスト

|型|型コード|説明|
|:----|:----|:----|
|int8/16/32/64|i1/i2/i4/i8| |
|float16/32/64/128| f2/f/d/g| |
|complex64/128/256 | c8/c16/c32 |複素数型 |
|bool|?||
|object|O|Pythonのオブジェクト型|
|string_|S||
|unicode_|U||

### astype
dtypeを明示的に型変換する
(必ず新規ndarrayが生成されることに注意)

In [32]:
arr = np.array([0,1,2,3,4,5])
print(arr.dtype, arr)
arr = arr.astype(np.float64)
print(arr.dtype, arr)
arr = arr.astype(np.complex64)
print(arr.dtype, arr)
arr = arr.astype(np.bool)
print(arr.dtype, arr)

int64 [0 1 2 3 4 5]
float64 [0. 1. 2. 3. 4. 5.]
complex64 [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
bool [False  True  True  True  True  True]


## 4.1.3 ndarrayの算術演算
ndarray間を比較した時、その結果は同要素数の真偽値配列として戻される.
サイズの異なるndarray同士の演算は**ブロードキャスト**と呼ばれる

In [48]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,1,4,3])

arr1 < arr2

array([ True, False,  True, False])

## 4.1.4 インデックス参照とスライシングの基礎
### 一次次元の場合

In [49]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
arr[4]

4

In [51]:
arr[4:8]

array([4, 5, 6, 7])

In [53]:
arr[4:8] = 12
print(arr)

[ 0  1  2  3 12 12 12 12  8  9]


リストと異なり, ndarrayのスライシングは切り出された元のndarrayの**ビュー**であり、値の変更はオリジナルに反映される.(**ブロードキャスト**)

In [57]:
arr_slice = arr[8:10]
print(arr_slice)

[8 9]


In [58]:
arr_slice[1] = 114
print(arr, arr_slice)

[  0   1   2   3  12  12  12  12   8 114] [  8 114]


ビューではなくコピーにしたい場合は明示的にcopy()をつける

In [61]:
arr_slice_copy = arr[0:6].copy() 
print(arr_slice_copy)

[ 0  1  2  3 12 12]


In [65]:
arr_slice_copy[:] = 0
print(arr, arr_slice_copy)

[  0   1   2   3  12  12  12  12   8 114] [0 0 0 0 0 0]


### N次元の場合
インデックス参照の手段が増える.

N = 2の場合, arr2d[0][1] または arr2d[0,1]で参照できる

## ブールインデックス参照
参照されたndarrayはコピーされたものであることに注意

In [66]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)

In [67]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [68]:
data

array([[-0.26137137, -0.27578319,  0.58236428, -0.63574719],
       [ 0.66365135,  0.56309523,  0.15481779,  0.05725008],
       [ 0.24389413,  1.51016652,  1.12187462,  0.09847997],
       [-0.66903941, -0.76626678, -0.40104834,  1.45914701],
       [-1.96764149, -0.16878813,  0.68619478, -1.04238164],
       [ 0.15220784,  1.5688388 , -0.56420524, -0.88325396],
       [-0.21069243, -0.84428861,  1.00826331,  0.08022791]])

dataから'Bob'に対応する行を抜き出す

In [69]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [70]:
data[ names == 'Bob' ]

array([[-0.26137137, -0.27578319,  0.58236428, -0.63574719],
       [-0.66903941, -0.76626678, -0.40104834,  1.45914701]])

列のスライスも同時に指定

In [71]:
data[names == 'Bob', 2:]

array([[ 0.58236428, -0.63574719],
       [-0.40104834,  1.45914701]])

In [72]:
data[names == 'Bob',3]

array([-0.63574719,  1.45914701])

In [73]:
data[data < 0]

array([-0.26137137, -0.27578319, -0.63574719, -0.66903941, -0.76626678,
       -0.40104834, -1.96764149, -0.16878813, -1.04238164, -0.56420524,
       -0.88325396, -0.21069243, -0.84428861])

In [75]:
data[data < 0 ] = 0
print(data)

[[0.         0.         0.58236428 0.        ]
 [0.66365135 0.56309523 0.15481779 0.05725008]
 [0.24389413 1.51016652 1.12187462 0.09847997]
 [0.         0.         0.         1.45914701]
 [0.         0.         0.68619478 0.        ]
 [0.15220784 1.5688388  0.         0.        ]
 [0.         0.         1.00826331 0.08022791]]


## 4.1.6 ファンシーインデックス参照
インデックス参照に整数配列を用いる方法のこと

arr からある特定の順序で行を抽出するには、その順番を示す**整数のリスト**あるいは**ndarray**をインデックス参照として渡す.

この参照の場合は必ず**一次元配列として返される**

In [77]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [78]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [79]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [81]:
arr = np.arange(32).reshape((8,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [82]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [83]:
arr[[1,5,2,7]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [ 8, 11,  9, 10],
       [28, 31, 29, 30]])

## 4.1.7 転置行列
ndarrayの転置は、オリジナル行列を再構成した特別なビューを戻す.コピーは生成しない.

方法
1. transpose関数
2. Tを参照
3. swapaxes関数

a.swapaxes(axis1, axis2)

Return a view of the array with `axis1` and `axis2` interchanged.

In [85]:
arr = np.arange(15).reshape((3,5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [86]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
arr = np.random.randn(6,3)
print(arr)

[[-0.36643434 -1.01681266 -0.71117774]
 [-2.01407877  0.68183995 -0.05359618]
 [-0.02202998 -1.90519697 -0.29148443]
 [-0.3080216  -0.4280681   0.15453725]
 [ 1.06834786 -0.33393087  1.30559478]
 [ 0.24735576 -1.27556379  1.0120655 ]]


In [88]:
np.dot(arr.T, arr)

array([[ 5.48870206, -1.49913101,  1.97253708],
       [-1.49913101,  7.05040432, -0.5511592 ],
       [ 1.97253708, -0.5511592 ,  3.34634556]])

高次元の場合,transposeの引数に軸の順序を与えることで入れ替えが可能.

In [91]:
arr = np.arange(16).reshape((2,2,4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


2番目の軸が先頭、1番目の軸が2番目, 三番目の軸はそのまま

In [93]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [96]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.2 ユニバーサル関数
ndarrayを対象に, 要素ごとの操作結果を戻す関数.

- 単項ufunc

|Function|Description|
|:--|:--|
|abs, fabs|絶対値計算, fabsは整数と小数のみ(高速)|
| sqrt | 平方根 |
| square | 二乗 |
| exp | 指数 |
| log, log10, log2, log1p| 1pは各要素に1を加えた数を真数として底eの対数計算 |
| sign | 各要素の符号を返す 正=>1, 0 => 0, 負=>-1 |
| ceil | 切り上げ |
| floor | 切り下げ |
| rint | 各要素の丸め値 |
| modf | 整数部分と小数部分に分割, 2つの配列を返す |
| isnan | NaNの真偽値配列 |
| isfinite, isinf | isfiniteは有限かどうか, isinfは無限かどうか |
| 三角関数及び逆散策関数|　|
| logiical_not | ~arrと同等 |
    
- 二項ufunc

|Function|Description|
|:--|:--|
| add/subtract/multiply/divide | 省略 |
| floor_divide | あまりを切り捨て |
| power | arr1を底, arr2要素でべき乗 |
| maximum/fmax | 配列の要素ごとの最大値を計算 maximumはNaNを選ぶ|
| minimum/fmin | |
| mod | 余剰計算 |
| copysign | arr1の値に,arr2の配列要素の符号をつける |

In [102]:
arr = np.arange(10)
print(np.sqrt(arr))
print(np.exp(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [106]:
arr1 = np.arange(10).reshape((2,5))
arr2 = arr1
np.power(arr1 ,arr2)

array([[        1,         1,         4,        27,       256],
       [     3125,     46656,    823543,  16777216, 387420489]])

# ndarrayによる配列指向プログラミング